DROP TYPE IF EXISTS attachment CASCADE;
DROP TYPE IF EXISTS role CASCADE;
DROP INDEX IF EXISTS idx_cm_user;
DROP INDEX IF EXISTS idx_messages_convo_created;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS friends CASCADE;
DROP TABLE IF EXISTS conversationsMembers CASCADE;
DROP TABLE IF EXISTS conversations CASCADE;
DROP TABLE IF EXISTS messages CASCADE;